# Uncomment the next line to define a global platform for your project

# platform :ios, '9.0'
target 'DjiAPI_port' do
pod 'MJExtension', '~> 3.0.13'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'IQKeyboardManager', '~> 4.0.13'
pod 'AFNetworking', '~> 3.1.0'
pod 'Reachability', '~> 3.2'
pod 'Bugly'
pod 'SocketRocket'
pod 'MJRefresh', '~> 3.1.15'
pod 'SDWebImage', '~> 4.2.1'
pod 'DJI-SDK-iOS'
pod 'DJI-SDK-iOS', '~> 4.8'
pod 'DJI-UXSDK-iOS'
pod 'DJIWidget', '~> 1.2'
end
